### ISSUE TITLE
thank you for this project! enjoy a beverage on me

### ISSUE THREAD

**Issue by deepthawtz** [stefanprodan/k8s-prom-hpa#14]
sorry to spam your github issues but I wanted to share my appreciation for your work

@GitCash send $5 BCH to @stefanprodan 🍻

**Comment by alwaysAn0n** [comment]
@GitCash send 5 usd to @stefanprodan :beers:

**Comment by GitCash** [comment]
Hey **stefanprodan**, user **alwaysAn0n** tipped you **7309 bits** in Bitcoin Cash ( ~ **$5** ).

*[Click here to claim it!](https://gitcash.io/claim/stefanprodan)*

You can also add the "thumbs down" reaction to **alwaysAn0n**'s comment above to prevent future tips.
