### ISSUE TITLE
Making certificate is throwing error.

### ISSUE THREAD

**Issue by gkarthiks** [stefanprodan/k8s-prom-hpa#2]
I am getting the below error when Irun the command `make certs` under the project folder.

```
Generating TLS certs
error: cannot open .git/FETCH_HEAD: Permission denied
package github.com/cloudflare/cfssl/cmd/cfssl: exit status 1
make: *** [gencerts] Error 1
```

**Comment by stefanprodan** [comment]
looks like you have a problem with your golang installation, does `go get -u github.com/cloudflare/cfssl/cmd/...` work?

**Comment by gkarthiks** [comment]
Actually i had to uninstall and re-install go.
Then its working as expected. Thank you for the response. 
One another question,
> I see we have to switch on `horizontal-pod-autoscaler-use-rest-clients` flag in the `kube-controller-manager`. But is that `kube-controller-manager` an addon?

**Comment by stefanprodan** [comment]
kube-controller-manager is not an add-on, it's a core component, see https://kubernetes.io/docs/reference/generated/kube-controller-manager/

**Comment by gkarthiks** [comment]
👍
