### ISSUE TITLE
Error on setting up custom metrics API server on AWS EKS.

### ISSUE THREAD

**Issue by stafot** [stefanprodan/k8s-prom-hpa#20]
Getting the following error `Error: cluster doesn't provide client-ca-file`
from the `quay.io/coreos/k8s-prometheus-adapter-amd64:v0.2.0`. 
I am not sure if it is related with this https://github.com/kubernetes/kubernetes/issues/65724 or is a misconfiguration on my AWS EKS cluster.
Any ideas would be appreciated.

**Comment by humayunjamal** [comment]
The fix works fine , it should be merged asap @stefanprodan

**Comment by stafot** [comment]
@humayunjamal https://github.com/stefanprodan/k8s-prom-hpa/pull/27#issuecomment-454332963 have you this problem too? Or does it work fine?
